name: GitHub Deployments
description: For creating and managing GitHub Deployments
author: https://github.com/wellcomecollection
requirements: []
configuration:
  properties:
    environment:
      type: string
    ref:
      type: string
    assume_role:
      type: string
  additionalProperties: false
