name: Build and publish plugin binaries
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Buildkite plugin
        run: yarn lint-plugin
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build binaries
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            bin/github-deployments-buildkite-plugin

